name: Setup Rust
description: Setup Rust environment for Deskulpt workflows.

inputs:
  platform:
    description: The platform to set up on.
    type: choice
    required: true
    default: ubuntu-latest
    options:
      - ubuntu-latest
      - macos-latest
      - windows-latest

  targets:
    description: Rust setup targets.
    type: string
    required: true
    default: ""

  components:
    description: Additional Rust components to install on top of the minimal profile.
    type: string
    required: true
    default: ""

  nightly-components:
    description: Rust components to install from the nightly toolchain.
    type: string
    required: true
    default: ""

  tools:
    description: Additional tools to install.
    type: string
    required: false

  cache-key:
    description: The cache key.
    type: string
    required: true
    default: ""
    options:
      - "" # Empty string never hits any cache, effectively disabling caching
      - debug

  save-cache:
    description: Whether to save the cache.
    type: boolean
    required: true
    default: false

runs:
  using: composite
  steps:
    - name: Install Linux dependencies
      if: inputs.platform == 'ubuntu-latest'
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.1-dev libayatana-appindicator3-dev librsvg2-dev

    - name: Parse toolchain version
      id: toolchain-version
      shell: bash
      run: |
        channel=$(grep -E '^\s*channel\s*=' rust-toolchain.toml | head -n1 | sed -E 's/.*=\s*"(.*)".*/\1/')
        echo "channel=$channel" >> $GITHUB_OUTPUT

    - name: Setup toolchain
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: ${{ steps.toolchain-version.outputs.channel }}
        components: ${{ inputs.components }}
        targets: ${{ inputs.targets }}

    - name: Setup cache
      uses: Swatinem/rust-cache@v2
      with:
        workspaces: . -> target
        shared-key: ${{ inputs.cache-key }}
        save-if: ${{ inputs.save-cache == 'true' }}
        cache-bin: false

    - name: Install nightly components
      if: ${{ inputs.nightly-components }}
      shell: bash
      run: |
        rustup toolchain install nightly --component ${{ inputs.nightly-components }} --profile minimal --no-self-update

    - name: Install tools
      uses: taiki-e/install-action@v2
      if: ${{ inputs.tools }}
      with:
        tool: ${{ inputs.tools }}
