packages:
  - packages/*
  - docs

catalog:
  "@emotion/react": ^11.14.0
  "@fontsource-variable/geist": ^5.2.8
  "@fontsource-variable/geist-mono": ^5.2.7
  "@orama/orama": ^3.1.16
  "@radix-ui/react-select": ^2.2.5
  "@radix-ui/themes": ^3.2.0
  "@rollup/plugin-replace": ^6.0.3
  "@rollup/plugin-terser": ^0.4.4
  "@rollup/plugin-typescript": ^12.3.0
  "@tailwindcss/vite": ^4.1.17
  "@tanstack/react-router": ^1.141.2
  "@tanstack/react-start": ^1.141.2
  "@tanstack/react-virtual": ^3.13.13
  "@tanstack/start-static-server-functions": ^1.141.2
  "@tauri-apps/api": ^2.9.1
  "@tauri-apps/cli": ^2.9.5
  "@tauri-apps/plugin-clipboard-manager": ^2.3.2
  "@tauri-apps/plugin-opener": ^2.5.2
  "@testing-library/jest-dom": ^6.6.3
  "@testing-library/react": ^16.1.0
  "@testing-library/user-event": ^14.5.2
  "@types/node": ^24.10.2
  "@types/react": ^19.2.7
  "@types/react-dom": ^19.2.3
  "@types/semver": ^7.7.1
  "@vitejs/plugin-react": ^5.1.2
  "@vitest/coverage-v8": ^4.0.15
  "@vitest/ui": ^4.0.15
  bowser: ^2.13.1
  fumadocs-core: 16.2.4
  fumadocs-mdx: 14.1.0
  fumadocs-ui: 16.2.4
  http-server: ^14.1.1
  husky: ^9.1.6
  jsdom: ^27.3.0
  knip: ^5.72.0
  lint-staged: ^16.2.7
  lucide-react: ^0.560.0
  motion: ^12.23.26
  oxlint: ^1.32.0
  prettier: ^3.7.4
  prettier-plugin-tailwindcss: ^0.7.2
  prettier-plugin-toml: ^2.0.6
  re-resizable: ^6.11.2
  react: ^19.2.1
  react-dom: ^19.2.1
  react-draggable: ^4.5.0
  react-error-boundary: ^6.0.0
  react-icons: ^5.5.0
  rollup: ^4.53.3
  semver: ^7.7.3
  sonner: ^2.0.7
  superjson: ^2.2.6
  tailwindcss: ^4.1.17
  tslib: ^2.8.1
  tw-animate-css: ^1.4.0
  typescript: ^5.9.3
  vite: ^7.2.7
  vite-tsconfig-paths: ^5.1.4
  vitest: ^4.0.15
  zod: ^4.1.13
  zustand: ^5.0.9
