packages:
  - packages/*

catalog:
  "@emotion/react": ^11.14.0
  "@radix-ui/themes": ^3.3.0
  "@rollup/plugin-replace": ^6.0.3
  "@rollup/plugin-terser": ^0.4.4
  "@rollup/plugin-typescript": ^12.3.0
  "@tanstack/react-virtual": ^3.13.18
  "@tauri-apps/api": ^2.9.1
  "@tauri-apps/cli": ^2.9.6
  "@tauri-apps/plugin-clipboard-manager": ^2.3.2
  "@tauri-apps/plugin-opener": ^2.5.3
  "@types/node": ^25.2.0
  "@types/react": ^19.2.10
  "@types/react-dom": ^19.2.3
  "@vitejs/plugin-react": ^5.1.3
  babel-plugin-react-compiler: ^1.0.0
  husky: ^9.1.6
  knip: ^5.82.1
  lint-staged: ^16.2.7
  oxlint: ^1.43.0
  prettier: ^3.8.1
  prettier-plugin-toml: ^2.0.6
  re-resizable: ^6.11.2
  react: ^19.2.4
  react-dom: ^19.2.4
  react-draggable: ^4.5.0
  react-error-boundary: ^6.1.0
  react-icons: ^5.5.0
  rollup: ^4.57.1
  sonner: ^2.0.7
  superjson: ^2.2.6
  tslib: ^2.8.1
  typescript: ^5.9.3
  vite: ^7.3.1
  zustand: ^5.0.11
