/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as LlmsDottxtRouteImport } from "./routes/llms[.]txt";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as ReleasesIndexRouteImport } from "./routes/releases/index";
import { Route as DocsIndexRouteImport } from "./routes/docs/index";
import { Route as ReleasesLatestRouteImport } from "./routes/releases/latest";
import { Route as ReleasesVersionRouteImport } from "./routes/releases/$version";
import { Route as DocsSplatRouteImport } from "./routes/docs/$";
import { Route as ApiSearchRouteImport } from "./routes/api/search";

const LlmsDottxtRoute = LlmsDottxtRouteImport.update({
  id: "/llms.txt",
  path: "/llms.txt",
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const ReleasesIndexRoute = ReleasesIndexRouteImport.update({
  id: "/releases/",
  path: "/releases/",
  getParentRoute: () => rootRouteImport,
} as any);
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: "/docs/",
  path: "/docs/",
  getParentRoute: () => rootRouteImport,
} as any);
const ReleasesLatestRoute = ReleasesLatestRouteImport.update({
  id: "/releases/latest",
  path: "/releases/latest",
  getParentRoute: () => rootRouteImport,
} as any);
const ReleasesVersionRoute = ReleasesVersionRouteImport.update({
  id: "/releases/$version",
  path: "/releases/$version",
  getParentRoute: () => rootRouteImport,
} as any);
const DocsSplatRoute = DocsSplatRouteImport.update({
  id: "/docs/$",
  path: "/docs/$",
  getParentRoute: () => rootRouteImport,
} as any);
const ApiSearchRoute = ApiSearchRouteImport.update({
  id: "/api/search",
  path: "/api/search",
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/llms.txt": typeof LlmsDottxtRoute;
  "/api/search": typeof ApiSearchRoute;
  "/docs/$": typeof DocsSplatRoute;
  "/releases/$version": typeof ReleasesVersionRoute;
  "/releases/latest": typeof ReleasesLatestRoute;
  "/docs": typeof DocsIndexRoute;
  "/releases": typeof ReleasesIndexRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/llms.txt": typeof LlmsDottxtRoute;
  "/api/search": typeof ApiSearchRoute;
  "/docs/$": typeof DocsSplatRoute;
  "/releases/$version": typeof ReleasesVersionRoute;
  "/releases/latest": typeof ReleasesLatestRoute;
  "/docs": typeof DocsIndexRoute;
  "/releases": typeof ReleasesIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/llms.txt": typeof LlmsDottxtRoute;
  "/api/search": typeof ApiSearchRoute;
  "/docs/$": typeof DocsSplatRoute;
  "/releases/$version": typeof ReleasesVersionRoute;
  "/releases/latest": typeof ReleasesLatestRoute;
  "/docs/": typeof DocsIndexRoute;
  "/releases/": typeof ReleasesIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/llms.txt"
    | "/api/search"
    | "/docs/$"
    | "/releases/$version"
    | "/releases/latest"
    | "/docs"
    | "/releases";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | "/llms.txt"
    | "/api/search"
    | "/docs/$"
    | "/releases/$version"
    | "/releases/latest"
    | "/docs"
    | "/releases";
  id:
    | "__root__"
    | "/"
    | "/llms.txt"
    | "/api/search"
    | "/docs/$"
    | "/releases/$version"
    | "/releases/latest"
    | "/docs/"
    | "/releases/";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  LlmsDottxtRoute: typeof LlmsDottxtRoute;
  ApiSearchRoute: typeof ApiSearchRoute;
  DocsSplatRoute: typeof DocsSplatRoute;
  ReleasesVersionRoute: typeof ReleasesVersionRoute;
  ReleasesLatestRoute: typeof ReleasesLatestRoute;
  DocsIndexRoute: typeof DocsIndexRoute;
  ReleasesIndexRoute: typeof ReleasesIndexRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/llms.txt": {
      id: "/llms.txt";
      path: "/llms.txt";
      fullPath: "/llms.txt";
      preLoaderRoute: typeof LlmsDottxtRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/releases/": {
      id: "/releases/";
      path: "/releases";
      fullPath: "/releases";
      preLoaderRoute: typeof ReleasesIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/docs/": {
      id: "/docs/";
      path: "/docs";
      fullPath: "/docs";
      preLoaderRoute: typeof DocsIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/releases/latest": {
      id: "/releases/latest";
      path: "/releases/latest";
      fullPath: "/releases/latest";
      preLoaderRoute: typeof ReleasesLatestRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/releases/$version": {
      id: "/releases/$version";
      path: "/releases/$version";
      fullPath: "/releases/$version";
      preLoaderRoute: typeof ReleasesVersionRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/docs/$": {
      id: "/docs/$";
      path: "/docs/$";
      fullPath: "/docs/$";
      preLoaderRoute: typeof DocsSplatRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/api/search": {
      id: "/api/search";
      path: "/api/search";
      fullPath: "/api/search";
      preLoaderRoute: typeof ApiSearchRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LlmsDottxtRoute: LlmsDottxtRoute,
  ApiSearchRoute: ApiSearchRoute,
  DocsSplatRoute: DocsSplatRoute,
  ReleasesVersionRoute: ReleasesVersionRoute,
  ReleasesLatestRoute: ReleasesLatestRoute,
  DocsIndexRoute: DocsIndexRoute,
  ReleasesIndexRoute: ReleasesIndexRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

import type { getRouter } from "./router.tsx";
import type { createStart } from "@tanstack/react-start";
declare module "@tanstack/react-start" {
  interface Register {
    ssr: true;
    router: Awaited<ReturnType<typeof getRouter>>;
  }
}
