//! Tauri commands.
#![doc = include_str!("../permissions/autogenerated/reference.md")]

use deskulpt_common::SerResult;
use serde::Deserialize;
use tauri::{AppHandle, Runtime, WebviewWindow};
use tracing::{debug, error, info, trace, warn};

use crate::LogsExt;
use crate::reader::{Cursor, Page};

/// Level of severity for logging.
#[derive(Debug, Deserialize, specta::Type)]
#[serde(rename_all = "camelCase")]
pub enum Level {
    /// At least the severity of [`tracing::Level::TRACE`].
    Trace,
    /// At least the severity of [`tracing::Level::DEBUG`].
    Debug,
    /// At least the severity of [`tracing::Level::INFO`].
    Info,
    /// At least the severity of [`tracing::Level::WARN`].
    Warn,
    /// At least the severity of [`tracing::Level::ERROR`].
    Error,
}

impl From<Level> for tracing::Level {
    fn from(level: Level) -> Self {
        match level {
            Level::Trace => tracing::Level::TRACE,
            Level::Debug => tracing::Level::DEBUG,
            Level::Info => tracing::Level::INFO,
            Level::Warn => tracing::Level::WARN,
            Level::Error => tracing::Level::ERROR,
        }
    }
}

/// Emit a log at the specified level.
///
/// This shares the logging system of the backend. Optional metadata can be
/// provided as arbitrary JSON-serializable value. If no metadata is needed,
/// pass `null`.
#[tauri::command]
#[specta::specta]
pub async fn log<R: Runtime>(
    window: WebviewWindow<R>,
    level: Level,
    message: String,
    meta: serde_json::Value,
) -> SerResult<()> {
    match window.label() {
        "canvas" => match level {
            Level::Trace => trace!(target: "frontend::canvas", %meta, message),
            Level::Debug => debug!(target: "frontend::canvas", %meta, message),
            Level::Info => info!(target: "frontend::canvas", %meta, message),
            Level::Warn => warn!(target: "frontend::canvas", %meta, message),
            Level::Error => error!(target: "frontend::canvas", %meta, message),
        },
        "manager" => match level {
            Level::Trace => trace!(target: "frontend::manager", %meta, message),
            Level::Debug => debug!(target: "frontend::manager", %meta, message),
            Level::Info => info!(target: "frontend::manager", %meta, message),
            Level::Warn => warn!(target: "frontend::manager", %meta, message),
            Level::Error => error!(target: "frontend::manager", %meta, message),
        },
        _ => {},
    }
    Ok(())
}

/// Read a page of log entries.
#[tauri::command]
#[specta::specta]
pub async fn read<R: Runtime>(
    app_handle: AppHandle<R>,
    limit: usize,
    min_level: Level,
    cursor: Option<Cursor>,
) -> SerResult<Page> {
    let page = app_handle.logs().read(limit, min_level.into(), cursor)?;
    Ok(page)
}

/// Clear all log files and return the freed disk space in bytes.
#[tauri::command]
#[specta::specta]
pub async fn clear<R: Runtime>(app_handle: AppHandle<R>) -> SerResult<u64> {
    let size = app_handle.logs().clear()?;
    Ok(size)
}
