//! Tauri commands.
#![doc = include_str!("../permissions/autogenerated/reference.md")]

use deskulpt_common::SerResult;
use tauri::{AppHandle, Runtime};

use crate::SettingsExt;
use crate::types::{Settings, SettingsPatch};

/// Get the current settings.
#[tauri::command]
#[specta::specta]
pub async fn read<R: Runtime>(app_handle: AppHandle<R>) -> SerResult<Settings> {
    let settings = app_handle.settings().read().clone();
    Ok(settings)
}

/// Update the settings with a patch.
///
/// Wrapper of [`crate::SettingsManager::update`].
#[tauri::command]
#[specta::specta]
pub async fn update<R: Runtime>(app_handle: AppHandle<R>, patch: SettingsPatch) -> SerResult<()> {
    app_handle.settings().update(patch)?;
    Ok(())
}
