//! Tauri commands.
#![doc = include_str!("../permissions/autogenerated/reference.md")]

use deskulpt_common::SerResult;
use deskulpt_core::logging::{
    TriggerContext, WidgetContext, attach_trigger, attach_widget_context,
};
use tauri::{AppHandle, Runtime, WebviewWindow};
use tracing::{Instrument, field, info_span};
use uuid::Uuid;

use crate::WidgetsExt;

/// Refresh a specific widget by its ID.
///
/// This command is a wrapper of [`crate::WidgetsManager::refresh`].
#[tauri::command]
#[specta::specta]
pub async fn refresh<R: Runtime>(app_handle: AppHandle<R>, id: String) -> SerResult<()> {
    let request_id = Uuid::new_v4();
    let span = info_span!(
        "widget_command",
        widget_id = %id,
        plugin_id = field::Empty,
        request_id = %request_id,
        tauri_command = "refresh",
    );
    let widget_ctx = WidgetContext::new(id.clone(), None);
    attach_widget_context(&span, widget_ctx.widget_id(), widget_ctx.plugin_id());
    attach_trigger(&span, TriggerContext::new("refresh", Some(widget_ctx)));

    async move {
        app_handle.widgets().refresh(&id)?;
        Ok(())
    }
    .instrument(span)
    .await
}

/// Refresh all widgets.
///
/// This command is a wrapper of [`crate::WidgetsManager::refresh_all`].
#[tauri::command]
#[specta::specta]
pub async fn refresh_all<R: Runtime>(app_handle: AppHandle<R>) -> SerResult<()> {
    app_handle.widgets().refresh_all()?;
    Ok(())
}

/// Mark a window as having completed setup.
///
/// Wrapper of [`crate::WidgetsManager::complete_setup`].
#[tauri::command]
#[specta::specta]
pub async fn complete_setup<R: Runtime>(
    app_handle: AppHandle<R>,
    window: WebviewWindow<R>,
) -> SerResult<()> {
    app_handle.widgets().complete_setup(window)?;
    Ok(())
}
