//! Tauri commands.
#![doc = include_str!("../permissions/autogenerated/reference.md")]

use deskulpt_common::SerResult;
use tauri::{AppHandle, Runtime, WebviewWindow};

use crate::WidgetsExt;
use crate::registry::RegistryIndex;

/// Refresh a specific widget by its ID.
///
/// This command is a wrapper of [`crate::WidgetsManager::refresh`].
#[tauri::command]
#[specta::specta]
pub async fn refresh<R: Runtime>(app_handle: AppHandle<R>, id: String) -> SerResult<()> {
    app_handle.widgets().refresh(&id)?;
    Ok(())
}

/// Refresh all widgets.
///
/// This command is a wrapper of [`crate::WidgetsManager::refresh_all`].
#[tauri::command]
#[specta::specta]
pub async fn refresh_all<R: Runtime>(app_handle: AppHandle<R>) -> SerResult<()> {
    app_handle.widgets().refresh_all()?;
    Ok(())
}

#[tauri::command]
#[specta::specta]
pub async fn fetch_registry_index<R: Runtime>(
    app_handle: AppHandle<R>,
) -> SerResult<RegistryIndex> {
    let index = app_handle.widgets().fetch_registry_index().await?;
    Ok(index)
}

#[tauri::command]
#[specta::specta]
pub async fn install<R: Runtime>(
    app_handle: AppHandle<R>,
    handle: String,
    id: String,
    digest: String,
) -> SerResult<()> {
    app_handle.widgets().install(&handle, &id, &digest).await?;
    Ok(())
}

#[tauri::command]
#[specta::specta]
pub async fn uninstall<R: Runtime>(
    app_handle: AppHandle<R>,
    handle: String,
    id: String,
) -> SerResult<()> {
    app_handle.widgets().uninstall(&handle, &id).await?;
    Ok(())
}

#[tauri::command]
#[specta::specta]
pub async fn upgrade<R: Runtime>(
    app_handle: AppHandle<R>,
    handle: String,
    id: String,
    digest: String,
) -> SerResult<()> {
    app_handle.widgets().upgrade(&handle, &id, &digest).await?;
    Ok(())
}

/// Mark a window as having completed setup.
///
/// Wrapper of [`crate::WidgetsManager::complete_setup`].
#[tauri::command]
#[specta::specta]
pub async fn complete_setup<R: Runtime>(
    app_handle: AppHandle<R>,
    window: WebviewWindow<R>,
) -> SerResult<()> {
    app_handle.widgets().complete_setup(window)?;
    Ok(())
}
