/*! Auto-generated by xtask-gen. DO NOT EDIT! */

import { invoke } from "@tauri-apps/api/core";

// =============================================================================
// Types
// =============================================================================

/**
 * Cursor for log pagination.
 */
export type Cursor = { 
/**
 * The rotating log file path.
 */
path: string; 
/**
 * The byte offset within the log file.
 * 
 * If offset is non-zero, there is older data in this file in [0, offset).
 * If offset is zero, this file is fully consumed and the next older
 * non-empty file should be read.
 */
offset: number }

/**
 * Deskulpt window enum.
 */
export type DeskulptWindow = 
/**
 * The manager window.
 */
"manager" | 
/**
 * The canvas window.
 */
"canvas"

/**
 * A single log entry.
 */
export type Entry = { 
/**
 * Timestamp of the log entry in RFC 3339 format.
 */
timestamp: string; 
/**
 * The logging level, all capitals.
 */
level: string; 
/**
 * The log message.
 */
message: string; 
/**
 * The raw JSON representation of the log entry.
 */
raw: JsonValue }

export type JsonValue = null | boolean | number | string | JsonValue[] | { [key in string]: JsonValue }

/**
 * Logging levels supported.
 * 
 * They correspond to the [`tracing::Level`] variants.
 */
export type Level = "trace" | "debug" | "info" | "warn" | "error"

/**
 * A page of log entries.
 */
export type Page = { 
/**
 * Log entries in reverse chronological order, i.e., newest first.
 */
entries: Entry[]; 
/**
 * Cursor for fetching the next page of older log entries.
 */
cursor: Cursor | null; 
/**
 * Whether there are more log entries available beyond this page.
 */
hasMore: boolean }


// =============================================================================
// Commands
// =============================================================================

export const commands = {
  /**
   * Clear all log files and return the freed disk space in bytes.
   * 
   * ### Errors
   * 
   * - Error discovering log files.
   */
  clear: () => invoke<number>("plugin:deskulpt-logs|clear"),

  /**
   * Fetch a page of log entries.
   * 
   * The limit specifies the maximum number of log entries to retrieve and must
   * be strictly positive. The cursor is for pagination. The first call should
   * pass `None` for the cursor to start from the newest log entries, and
   * subsequent calls should use the cursor returned from the previous call to
   * fetch older entries. `min_level` filters log entries to only those at or
   * above the specified logging level (ordered by severity).
   * 
   * ### Errors
   * 
   * - The limit is zero.
   * - Failed to retrieve metadata of log files.
   * - Failed to read log files.
   */
  read: (
    limit: number,
    cursor: Cursor | null,
    minLevel: Level,
  ) => invoke<Page>("plugin:deskulpt-logs|read", {
    limit,
    cursor,
    minLevel,
  }),

  /**
   * Log a message at the specified level from the frontend.
   * 
   * Optional metadata can be provided as a JSON value. If no metadata is needed,
   * pass null.
   */
  log: (
    level: Level,
    message: string,
    meta: JsonValue,
  ) => invoke<null>("plugin:deskulpt-logs|log", {
    level,
    message,
    meta,
  }),
};
