/*! Auto-generated by xtask-gen. DO NOT EDIT! */

import { invoke } from "@tauri-apps/api/core";
import * as tauriEvent from "@tauri-apps/api/event";

// =============================================================================
// Types
// =============================================================================

/**
 * Deskulpt window enum.
 */
export type DeskulptWindow = 
/**
 * The manager window.
 */
"manager" | 
/**
 * The canvas window.
 */
"canvas"

export type JsonValue = null | boolean | number | string | JsonValue[] | { [key in string]: JsonValue }

/**
 * A single parsed log entry.
 */
export type LogEntry = { timestamp: string; level: string; message: string; fields: string | null }

/**
 * Metadata describing a log file on disk.
 */
export type LogFileInfo = { name: string; size: number; modified: string }

/**
 * Log levels accepted from the frontend.
 */
export type LoggingLevel = "trace" | "debug" | "info" | "warn" | "error"

/**
 * Event for showing a toast notification.
 * 
 * This event is emitted from the backend to the canvas window when a toast
 * notification needs to be displayed.
 */
export type ShowToastEvent = 
/**
 * Show a [success](https://sonner.emilkowal.ski/toast#success) toast.
 */
{ type: "success"; content: string } | 
/**
 * Show an [error](https://sonner.emilkowal.ski/toast#error) toast.
 */
{ type: "error"; content: string }

// =============================================================================
// Events
// =============================================================================

function makeEvent<T>(name: string) {
  return {
    /** The name of the event. */
    name,
    /** Listen for the event. */
    listen: (cb: tauriEvent.EventCallback<T>, options?: tauriEvent.Options) =>
      tauriEvent.listen(name, cb, options),
    /** Listen once for the event. */
    once: (cb: tauriEvent.EventCallback<T>, options?: tauriEvent.Options) =>
      tauriEvent.once(name, cb, options),
    /** Emit the event to all targets. */
    emit: (payload: T) => tauriEvent.emit(name, payload),
    /** Emit the event to a specific Deskulpt window. */
    emitTo: (window: DeskulptWindow, payload: T) =>
      tauriEvent.emitTo(window, name, payload),
  };
}

export const events = {
  showToast: makeEvent<ShowToastEvent>("deskulpt-core://show-toast"),
};

// =============================================================================
// Commands
// =============================================================================

export const commands = {
  /**
   * Call a plugin command (🚧 TODO 🚧).
   * 
   * ### 🚧 TODO 🚧
   * 
   * The Deskulpt core should keep a state of the registered plugins and call the
   * plugins dynamically. Also, instead of invoking the plugins directly, the
   * Deskulpt core should not depend on any of the plugins and should use IPC to
   * communicate with the plugins.
   * 
   * Also, in order to simplify the engine API for the plugin (because it is
   * a temporary implementation), `app_handle` is using the default runtime but
   * it should be a generic `R: Runtime` parameter in the final implementation.
   */
  callPlugin: (
    plugin: string,
    command: string,
    id: string,
    payload: JsonValue | null,
  ) => invoke<JsonValue>("plugin:deskulpt-core|call_plugin", {
    plugin,
    command,
    id,
    payload,
  }),

  /**
   * Open the widgets directory or a specific widget directory.
   * 
   * If the widget ID is provided, a specific widget directory will be opened.
   * Otherwise, the widgets directory will be opened.
   * 
   * ### Errors
   * 
   * - Widget ID is provided but does not exist in the collection.
   * - Failed to access the widgets directory.
   * - Error opening the directory.
   */
  openWidget: (
    id: string | null,
  ) => invoke<null>("plugin:deskulpt-core|open_widget", {
    id,
  }),


  openLogsDir: () => invoke<null>("plugin:deskulpt-core|open_logs_dir"),


  log: (
    level: LoggingLevel,
    message: string,
    meta: JsonValue,
  ) => invoke<null>("plugin:deskulpt-core|log", {
    level,
    message,
    meta,
  }),


  listLogs: () => invoke<LogFileInfo[]>("plugin:deskulpt-core|list_logs"),


  readLog: (
    filename: string,
    limit: number,
  ) => invoke<LogEntry[]>("plugin:deskulpt-core|read_log", {
    filename,
    limit,
  }),


  clearLogs: () => invoke<null>("plugin:deskulpt-core|clear_logs"),
};
