/*! Auto-generated by xtask-gen. DO NOT EDIT! */

import { invoke } from "@tauri-apps/api/core";
import * as tauriEvent from "@tauri-apps/api/event";

// =============================================================================
// Types
// =============================================================================

/**
 * Deskulpt window enum.
 */
export type DeskulptWindow = 
/**
 * The manager window.
 */
"manager" | 
/**
 * The canvas window.
 */
"canvas"

/**
 * Full settings of the Deskulpt application.
 */
export type Settings = { 
/**
 * The application theme.
 */
theme: Theme; 
/**
 * The keyboard shortcuts.
 * 
 * This maps the actions to the shortcut strings that will trigger them.
 */
shortcuts: Partial<{ [key in ShortcutAction]: string }>; 
/**
 * The mapping from widget IDs to their respective settings.
 */
widgets: { [key in string]: WidgetSettings } }

/**
 * A patch for partial updates to [`Settings`].
 */
export type SettingsPatch = { 
/**
 * If not `None`, update [`Settings::theme`].
 */
theme?: Theme; 
/**
 * If not `None`, update [`Settings::shortcuts`].
 * 
 * Non-specified shortcuts will remain unchanged. If a shortcut value is
 * `None`, it means removing that shortcut. Otherwise, it means updating
 * or adding that shortcut.
 */
shortcuts?: Partial<{ [key in ShortcutAction]: string | null }>; 
/**
 * If not `None`, update [`Settings::widgets`].
 * 
 * Non-specified widgets will remain unchanged. If a widget settings patch
 * is `None`, it means removing that widget. Otherwise, it means applying
 * the patch to that widget settings. If the widget ID does not exist, a
 * new widget settings will be created with default values, and then the
 * patch will be applied to it.
 */
widgets?: { [key in string]: WidgetSettingsPatch | null } }

/**
 * Actions that can be bound to keyboard shortcuts.
 */
export type ShortcutAction = 
/**
 * Toggle the canvas interaction mode (imode).
 */
"toggleCanvasImode" | 
/**
 * Open the manager interface.
 */
"openManager"

/**
 * The light/dark theme of the application interface.
 */
export type Theme = "light" | "dark"

/**
 * Event for notifying frontend windows of a settings update.
 */
export type UpdateEvent = Settings

/**
 * Per-widget settings.
 */
export type WidgetSettings = { 
/**
 * The leftmost x-coordinate in pixels.
 */
x: number; 
/**
 * The topmost y-coordinate in pixels.
 */
y: number; 
/**
 * The width in pixels.
 */
width: number; 
/**
 * The height in pixels.
 */
height: number; 
/**
 * The opacity in percentage.
 */
opacity: number }

/**
 * A patch for partial updates to [`WidgetSettings`].
 */
export type WidgetSettingsPatch = { 
/**
 * If not `None`, update [`WidgetSettings::x`].
 */
x?: number; 
/**
 * If not `None`, update [`WidgetSettings::y`].
 */
y?: number; 
/**
 * If not `None`, update [`WidgetSettings::width`].
 */
width?: number; 
/**
 * If not `None`, update [`WidgetSettings::height`].
 */
height?: number; 
/**
 * If not `None`, update [`WidgetSettings::opacity`].
 */
opacity?: number }

// =============================================================================
// Events
// =============================================================================

function makeEvent<T>(name: string) {
  return {
    /** The name of the event. */
    name,
    /** Listen for the event. */
    listen: (cb: tauriEvent.EventCallback<T>, options?: tauriEvent.Options) =>
      tauriEvent.listen(name, cb, options),
    /** Listen once for the event. */
    once: (cb: tauriEvent.EventCallback<T>, options?: tauriEvent.Options) =>
      tauriEvent.once(name, cb, options),
    /** Emit the event to all targets. */
    emit: (payload: T) => tauriEvent.emit(name, payload),
    /** Emit the event to a specific Deskulpt window. */
    emitTo: (window: DeskulptWindow, payload: T) =>
      tauriEvent.emitTo(window, name, payload),
  };
}

export const events = {
  update: makeEvent<UpdateEvent>("deskulpt-settings://update"),
};

// =============================================================================
// Commands
// =============================================================================

export const commands = {
  /**
   * Update the settings with a patch.
   * 
   * Wrapper of [`crate::SettingsManager::update`].
   */
  update: (
    patch: SettingsPatch,
  ) => invoke<null>("plugin:deskulpt-settings|update", {
    patch,
  }),
};
