/*! Auto-generated by xtask-gen. DO NOT EDIT! */

import { invoke } from "@tauri-apps/api/core";

// =============================================================================
// Types
// =============================================================================

/**
 * Cursor for log pagination.
 */
export type Cursor = { 
/**
 * The rotating log file path.
 */
path: string; 
/**
 * The byte offset within the log file.
 * 
 * If offset is non-zero, there is older data in this file in [0, offset).
 * If offset is zero, this file is fully consumed and the next older
 * non-empty file should be read.
 */
offset: number }

/**
 * Deskulpt window enum.
 */
export type DeskulptWindow = 
/**
 * The manager window.
 */
"manager" | 
/**
 * The canvas window.
 */
"canvas"

/**
 * A single log entry.
 */
export type Entry = { 
/**
 * Timestamp of the log entry in RFC 3339 format.
 */
timestamp: string; 
/**
 * The logging level, all capitals.
 */
level: string; 
/**
 * The log message.
 */
message: string; 
/**
 * The raw JSON representation of the log entry.
 */
raw: JsonValue }

export type JsonValue = null | boolean | number | string | JsonValue[] | { [key in string]: JsonValue }

/**
 * Level of severity for logging.
 */
export type Level = 
/**
 * At least the severity of [`tracing::Level::TRACE`].
 */
"trace" | 
/**
 * At least the severity of [`tracing::Level::DEBUG`].
 */
"debug" | 
/**
 * At least the severity of [`tracing::Level::INFO`].
 */
"info" | 
/**
 * At least the severity of [`tracing::Level::WARN`].
 */
"warn" | 
/**
 * At least the severity of [`tracing::Level::ERROR`].
 */
"error"

/**
 * A page of log entries.
 */
export type Page = { 
/**
 * Log entries in reverse chronological order, i.e., newest first.
 */
entries: Entry[]; 
/**
 * Cursor for reading the next page of older log entries.
 */
cursor: Cursor | null; 
/**
 * Whether there are more log entries available beyond this page.
 */
hasMore: boolean }


// =============================================================================
// Commands
// =============================================================================

export const commands = {
  /**
   * Clear all log files and return the freed disk space in bytes.
   */
  clear: () => invoke<number>("plugin:deskulpt-logs|clear"),

  /**
   * Read a page of log entries.
   */
  read: (
    limit: number,
    minLevel: Level,
    cursor: Cursor | null,
  ) => invoke<Page>("plugin:deskulpt-logs|read", {
    limit,
    minLevel,
    cursor,
  }),

  /**
   * Emit a log at the specified level.
   * 
   * This shares the logging system of the backend. Optional metadata can be
   * provided as arbitrary JSON-serializable value. If no metadata is needed,
   * pass `null`.
   */
  log: (
    level: Level,
    message: string,
    meta: JsonValue,
  ) => invoke<null>("plugin:deskulpt-logs|log", {
    level,
    message,
    meta,
  }),
};
