/*! Auto-generated by xtask-gen. DO NOT EDIT! */

import { invoke } from "@tauri-apps/api/core";
import * as tauriEvent from "@tauri-apps/api/event";

// =============================================================================
// Types
// =============================================================================

/**
 * Deskulpt window enum.
 */
export type DeskulptWindow = 
/**
 * The manager window.
 */
"manager" | 
/**
 * The canvas window.
 */
"canvas"

/**
 * A result-like binary outcome.
 * 
 * This represents the outcome of an operation that can either succeed with a
 * value of type `T` or fail with an error message.
 */
export type Outcome<T> = { type: "ok"; content: T } | { type: "err"; content: string }

/**
 * Event for reporting the rendering result of a widget to the canvas.
 */
export type RenderEvent = { 
/**
 * The ID of the widget.
 */
id: string; 
/**
 * Either the code string to render or a bundling error message.
 */
report: Outcome<string> }

/**
 * Event for notifying frontend windows of a widget catalog update.
 */
export type UpdateEvent = WidgetCatalog

/**
 * The catalog of Deskulpt widgets.
 * 
 * This keeps a mapping from widget IDs to their manifests (if valid) or error
 * messages (if invalid).
 */
export type WidgetCatalog = { [key in string]: Outcome<WidgetManifest> }

/**
 * Deskulpt widget manifest.
 */
export type WidgetManifest = 
/**
 * The metadata of the widget.
 */
({ 
/**
 * The display name of the widget.
 */
name: string; 
/**
 * The version of the widget.
 */
version?: string; 
/**
 * The authors of the widget.
 */
authors?: string[]; 
/**
 * The license of the widget.
 */
license?: string; 
/**
 * A short description of the widget.
 */
description?: string })

// =============================================================================
// Events
// =============================================================================

function makeEvent<T>(name: string) {
  return {
    /** The name of the event. */
    name,
    /** Listen for the event. */
    listen: (cb: tauriEvent.EventCallback<T>, options?: tauriEvent.Options) =>
      tauriEvent.listen(name, cb, options),
    /** Listen once for the event. */
    once: (cb: tauriEvent.EventCallback<T>, options?: tauriEvent.Options) =>
      tauriEvent.once(name, cb, options),
    /** Emit the event to all targets. */
    emit: (payload: T) => tauriEvent.emit(name, payload),
    /** Emit the event to a specific Deskulpt window. */
    emitTo: (window: DeskulptWindow, payload: T) =>
      tauriEvent.emitTo(window, name, payload),
  };
}

export const events = {
  render: makeEvent<RenderEvent>("deskulpt-widgets://render"),
  update: makeEvent<UpdateEvent>("deskulpt-widgets://update"),
};

// =============================================================================
// Commands
// =============================================================================

export const commands = {
  /**
   * Mark a window as having completed setup.
   * 
   * Wrapper of [`crate::WidgetsManager::complete_setup`].
   */
  completeSetup: () => invoke<null>("plugin:deskulpt-widgets|complete_setup"),

  /**
   * Refresh a specific widget by its ID.
   * 
   * This command is a wrapper of [`crate::WidgetsManager::refresh`].
   */
  refresh: (
    id: string,
  ) => invoke<null>("plugin:deskulpt-widgets|refresh", {
    id,
  }),

  /**
   * Refresh all widgets.
   * 
   * This command is a wrapper of [`crate::WidgetsManager::refresh_all`].
   */
  refreshAll: () => invoke<null>("plugin:deskulpt-widgets|refresh_all"),
};
