/*! Auto-generated by xtask-gen. DO NOT EDIT! */

import { invoke } from "@tauri-apps/api/core";

// =============================================================================
// Types
// =============================================================================

/**
 * Cursor for log pagination.
 */
export type Cursor = { 
/**
 * The index of the log file in the files list.
 */
fileIdx: number; 
/**
 * The byte offset within the log file.
 * 
 * When continuing from this cursor, reading resumes backwards from this
 * offset. An offset of zero means this file has been fully read, and the
 * reader should move to the next older file.
 */
offset: number }

/**
 * Deskulpt window enum.
 */
export type DeskulptWindow = 
/**
 * The manager window.
 */
"manager" | 
/**
 * The canvas window.
 */
"canvas"

/**
 * A single log entry.
 */
export type Entry = { 
/**
 * Timestamp of the log entry in RFC 3339 format.
 */
timestamp: string; 
/**
 * The stringified logging level (e.g., "INFO", "ERROR").
 */
level: string; 
/**
 * The log message text.
 */
message: string; 
/**
 * The complete raw JSON object representing the log entry.
 */
raw: JsonValue }

export type JsonValue = null | boolean | number | string | JsonValue[] | { [key in string]: JsonValue }

/**
 * Level of severity for logging.
 */
export type Level = 
/**
 * At least the severity of [`tracing::Level::TRACE`].
 */
"trace" | 
/**
 * At least the severity of [`tracing::Level::DEBUG`].
 */
"debug" | 
/**
 * At least the severity of [`tracing::Level::INFO`].
 */
"info" | 
/**
 * At least the severity of [`tracing::Level::WARN`].
 */
"warn" | 
/**
 * At least the severity of [`tracing::Level::ERROR`].
 */
"error"

/**
 * A page of log entries.
 */
export type Page = { 
/**
 * Log entries in reverse chronological order (most recent first).
 */
entries: Entry[]; 
/**
 * Cursor for reading the next page of older log entries.
 * 
 * If `None`, there are no more entries to read beyond this page.
 */
cursor: Cursor | null }


// =============================================================================
// Commands
// =============================================================================

export const commands = {
  /**
   * Clear all log files and return the freed disk space in bytes.
   */
  clear: () => invoke<number>("plugin:deskulpt-logs|clear"),

  /**
   * Read a page of log entries.
   */
  read: (
    limit: number,
    minLevel: Level,
    cursor: Cursor | null,
  ) => invoke<Page>("plugin:deskulpt-logs|read", {
    limit,
    minLevel,
    cursor,
  }),

  /**
   * Emit a log message at the specified level.
   * 
   * This integrates with the backend's logging system. Logs are automatically
   * tagged with the window label. Optional metadata can be provided as any
   * JSON-serializable value. Pass `null` if no metadata is needed.
   */
  log: (
    level: Level,
    message: string,
    meta: JsonValue,
  ) => invoke<null>("plugin:deskulpt-logs|log", {
    level,
    message,
    meta,
  }),
};
