/*! Auto-generated by xtask-gen. DO NOT EDIT! */

export * as deskulptCore from "./deskulpt-core.ts";
export * as deskulptSettings from "./deskulpt-settings.ts";
export * as deskulptWidgets from "./deskulpt-widgets.ts";
